### PR TITLE
Multivariable text fixes

### LINKED ISSUE #1009: MVT throws an SyntaxError when removing previously typed fields for a moment
### Describe the bug

A SyntaxError is thrown briefly when trying to parse a non-JSON string to JSON:

```
Unexpected token 'i', "first name" is not valid JSON
```

This appears to apply a variable name from the previous list of JSON variables.

### To Reproduce

* Create an MVT field
* Type some content with 1 or more variables
* lose focus on the field
* edit the field again, use the mouse to select all text then replace it with something without variables
* lose focus

### Expected behavior

No JSON error should be thrown

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui):
- pdfme version:
- Operating system:
- Node.js version or Browser name & version:
```

### Your Error Log

```shell
SyntaxError: Unexpected token 'a', "names" is not valid JSON
    at JSON.parse (<anonymous>)
    at substituteVariables (helper.js?t=1747379785557:11:24)
    at uiRender (uiRender.js?t=1747379785998:15:50)
    at index.es.js:153217:12
    at Zc (index.es.js:3529:24)
    at Sf (index.es.js:4365:24)
    at a.unstable_runWithPriority (index.es.js:551:16)
    at Xn (index.es.js:2264:23)
    at Da (index.es.js:4349:23)
    at Ms (index.es.js:3991:9)
```

### Additional context

This appears to be due to the following code in Renderer.tsx:

```
          if (mode !== 'designer' && schema.readOnly) {
            const variables = {
              ...schemasList.flat().reduce(
                (acc, currSchema) => {
                  acc[currSchema.name] = currSchema.content || '';
                  return acc;
                },
                {} as Record<string, string>,
              ),
              totalPages: schemasList.length,
              currentPage: index + 1,
            };

            value = replacePlaceholders({ content, variables, schemas: schemasList });
          }
```

An MVT field should only be `readOnly` when it has no variables, so normally this isn't a problem. It seems that due to the sequence of changes the readOnly is set briefly before the variables are emptied - leaving placeholders that this code picks up and tries to replace.

### PR DESCRIPTION
**Pull request by peteward**
fixes #1009 #1008

### CODE REVIEW

File: packages/schemas/src/multiVariableText/propPanel.ts [hunk 1]
```diff
@@ -15,6 +15,7 @@ const mapDynamicVariables = (props: PropPanelWidgetProps) => {
     changeSchemas([
       { key: 'content', value: JSON.stringify(variables), schemaId: activeSchema.id },
       { key: 'variables', value: varNames, schemaId: activeSchema.id },
+      { key: 'readOnly', value: varNames.length === 0, schemaId: activeSchema.id },
```
Comment (peteward) [inline packages/schemas/src/multiVariableText/propPanel.ts:18]: setting readOnly here, at the same time as the variables and content works around the #1009 problem

File: packages/ui/src/components/Renderer.tsx [hunk 2]
```diff
@@ -147,13 +153,7 @@ const Renderer = (props: RendererProps) => {
         ref.current.innerHTML = '';
       }
     };
-  }, [plugin?.ui, schema.type, reRenderDependencies]);
```
Comment (peteward) [inline packages/ui/src/components/Renderer.tsx:150]: the main bug here, introduced by devin, was that `reRenderDependencies` is already an array and nesting it didn't work properly

the other checks are not necessary because we've move a check for `plugin` and `plugin.ui` further up so they must exist (along with `schema.type`)

File: packages/ui/src/components/Renderer.tsx [hunk 3]
```diff
@@ -147,9 +147,9 @@ const Renderer = (props: RendererProps) => {
...
+  }, reRenderDependencies);
```
Comment (peteward) [inline packages/ui/src/components/Renderer.tsx:150]: the main problem was here that `reRenderDependencies` is already an array and nesting it seemed to break this

**Review by hand-dot — APPROVED** [review]
LGTM
