### PR TITLE
Fix dynamic font size vertical fit to use a more accurate height calculations 

### LINKED ISSUE #249: Dynamic font sizing (vertical fit) isn't considering font line heights properly
### Describe the bug

With most fonts, the dynamic font sizing is not properly considering their line height, with the issue seemingly proportional to the base line height of the font:

Screenshot 2023-08-27 at 07 28 29

### To Reproduce

* Create a text schema
* Set dynamic font sizing
* Give it a very high max and a very low min
* Type a long sentence
* Now keep increasing the line height
There will come a point where the font exceeds the container

### Expected behavior

The font should remain within the container down to the minimum font size.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): generator and ui
- pdfme version: latest main
- Operating system: osx
- Node.js version or Browser name & version: v18, chrome latest
```

### Your Error Log

```shell
-
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by peteward**
fixes #249 

Updates the dynamic font size calculations to use the same logic as PDF generation text positioning to give a better use of available height.

Before:
Screenshot 2023-08-28 at 14 47 53

After:
Screenshot 2023-08-28 at 14 47 39

### CODE REVIEW

File: packages/common/src/font.ts [hunk 1]
```diff
@@ -276,25 +276,30 @@ export const calculateDynamicFontSize = async ({
...
+      lines.forEach((line, lineIndex) => {
         if (dynamicFontFit === DYNAMIC_FIT_VERTICAL) {
           // For vertical fit we want to consider the width of text lines where we detect a split
           const textWidth = widthOfTextAtSize(line, fontKitFont, size, characterSpacing);
           const textWidthInMm = pt2mm(textWidth);
           totalWidthInMm = Math.max(totalWidthInMm, textWidthInMm);
         }
 
-        totalHeightInMm += textHeightInMm;
+        if (paraIndex + lineIndex === 0) {
```
Comment (hand-dot) [inline packages/common/src/font.ts:298]: Ah.... I understand. you are very cool.

**Review by hand-dot — APPROVED** [review]
